Neos:
  Neos:
    nodeTypes:
      groups:
        structureitem:
          position: 200
          label: 'Structure Item'


Nguonchhay:
  NodeTypeGenerator:
    nodeType:
      superTypes:
        'Neos.NodeTypes:TitleMixin': 'Title'
        'Neos.NodeTypes:TextMixin': 'Text'
        'Neos.NodeTypes:ImageMixin': 'Image'
        'Neos.NodeTypes:LinkMixin': 'Link'
        'Neos.NodeTypes:ContentReferences': 'Content references'
        'Neos.NodeTypes:AssetList': 'Assets'
      validators:
        'Neos.Neos/Validation/NotEmptyValidator': 'Not empty'
        'Neos.Neos/Validation/DateTimeValidator': 'DateTime validator'
        'Neos.Neos/Validation/FloatValidator': 'Float validator'
        'Neos.Neos/Validation/IntegerValidator': 'Integer validator'
        'Neos.Neos/Validation/NumberRangeValidator': 'Number range validator'
      propertyTypes:
        'boolean': 'Boolean'
        'integer': 'Integer'
        'string': 'String'
        'Neos\Media\Domain\Model\ImageInterface': 'Image'
        'DateTime': 'Date time'
        'reference': 'Reference'
        'references': 'References'
        'Neos\Media\Domain\Model\Asset': 'Asset'
        'array<Neos\Media\Domain\Model\Asset>': 'Asset list'
      groups:
        'general': 'General'
        'structure': 'Structure'
        'structureitem': 'Structure item'
      editors:
        'default': 'Text'
        'Neos.Neos/Inspector/Editors/TextAreaEditor': 'Text area'
        'Neos.Neos/Inspector/Editors/SelectBoxEditor': 'Select'
        'Neos.Neos/Inspector/Editors/LinkEditor': 'Link'
    fontAwesome: 'http://fontawesome.io/icons'
    staticTemplatePath: 'resource://Nguonchhay.NodeTypeGenerator/Private/StaticTemplates'
